spring.application.name=firstproject

#CONFIGURAÇÃO DO BANCO DE DADOS:    #springProduto=nome do database, pode ser outro, só substituir abaixo
spring.datasource.url=jdbc:mysql://localhost:3306/springProduto?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=bancodedados1234

#   DRIVER DO MYSQL
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

#configuração do Hibernate (JPA):
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



#   --------------------------------------------------------------------------------    #
# SE FOSSE UM ARQUIVO applicatio.yml SERIA NESSE FORMATO DE CONFIGURAÇÃO, TIPO JSON:

# spring:
#     application:
#         name: firstproject
#     datasource:
#         url: jdbc:mysql://localhost:3306/springProduto?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
#         username: root
#         password: bancodedados1234
#         driver-class-name: com.mysql.cj.jdbc.Driver
#     jpa:
#     database-platform: org.hibernate.dialect.MySQL8Dialect
#     hibernate:
#         ddl-auto: update
#     show-sql: true

#   --------------------------------------------------------------------------------    #